[package]
name = "pfcli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "pf"
path = "src/main.rs"

[dependencies]
portfolio-core = { path = "../portfolio-core" }
image-converter = { path = "../image-converter" }
docx-converter = { path = "../docx-converter" }
clap = { version = "4.5", features = ["derive"] }
anyhow = "1"
